export const loadingPhrases = [
	"Climbing into the Sunlit Roof of the Rainforest",
	"Threading Through the Amazon's Highest Branches",
	"Searching the Crowns for Hidden Life",
	"Rising Above the Rainforest Floor",
	"Exploring a World That Never Touches Ground",
	"Following the Light Through the Treetops",

	"Swinging Through Borneo's Treetop World",
	"Gripping Tight in the Lowland Canopy",
	"Tracing a Life Lived Entirely Aloft",
	"Following Silent Leaps Between Branches",
	"Venturing Into Borneo's Vertical Realm",
	"Balancing High Above the Forest Floor",

	"Wandering Europe's Last Primeval Forest",
	"Stepping Into Białowieża's Ancient Shadows",
	"Listening to Oaks That Have Stood for Centuries",
	"Tracing Bison Trails Through Old Growth",
	"Uncovering Life in the Fallen Timber",
	"Entering a Forest Time Forgot",

	"Descending Into the Amazon's Green Cathedral",
	"Losing Ourselves in the World's Richest Forest",
	"Following the Rain That Never Stops",
	"Uncovering One in Ten of Earth's Species",
	"Pushing Through the Amazon's Dripping Heart",
	"Tracing Life Layer by Layer to the Canopy",

	"Basking in California's Golden Oak Groves",
	"Wandering the Space Between Forest and Field",
	"Following Sunlight Through Scattered Oaks",
	"Enduring the Long Californian Drought",
	"Tracing Life Beneath Ancient Valley Oaks",
	"Crossing the Open Woodland at Dusk",

	"Riding the Winds of the Prairie Sea",
	"Tracing Roots Beneath an Ocean of Grass",
	"Following the Herds Across the Open Plains",
	"Enduring Fire, Frost, and Drought Alike",
	"Crossing a Horizon Without a Single Tree",
	"Uncovering Life Beneath the Prairie Sod",

	"Chasing the Great Serengeti Migration",
	"Crossing the Acacia-Studded Plains",
	"Following a Million Wildebeest Home",
	"Waiting Out the Long Dry Season",
	"Tracing Life Beneath the Flat-Topped Trees",
	"Racing the Rains Across the Savanna",

	"Surviving the Sonoran's Blazing Silence",
	"Waiting for Rain in a Land That Rarely Sees It",
	"Sheltering From the Desert's Merciless Sun",
	"Tracing Life Among the Saguaro at Night",
	"Enduring Where Little Else Can Survive",
	"Crossing a Landscape Built on Scarcity",

	"Braving Siberia's Frozen Horizon",
	"Racing Against the Short Arctic Summer",
	"Enduring a Ground That Never Fully Thaws",
	"Crossing the Treeless Permafrost Plain",
	"Surviving the Long Polar Dark",
	"Tracing Life on the Edge of the Frozen World",

	"Ascending Into Thin Himalayan Air",
	"Braving Cold, Wind, and Fierce Sun",
	"Climbing Beyond Where Trees Can Grow",
	"Tracing Life Above the Clouds",
	"Enduring the Roof of the World",
	"Following Hardy Life Onto Bare Rock",

	"Feeling Our Way Through Eternal Darkness",
	"Descending Into a World Without Light",
	"Tracing Life That Has Given Up Sight",
	"Uncovering Millions of Years in Limestone",
	"Venturing Where No Sunlight Has Ever Reached",
	"Following Blind Life Through the Silent Dark",

	"Riding the Pantanal's Rising Flood",
	"Tracing Life Through the Great Wet Pulse",
	"Following Waters That Reshape a Continent",
	"Uncovering the World's Largest Wetland",
	"Crossing Land That Drowns Each Year",
	"Gathering Where Flood Meets Abundance",

	"Tracing the Okavango's Vanishing River",
	"Following Water Into the Heart of the Desert",
	"Uncovering a Delta That Never Reaches the Sea",
	"Drifting Through the Kalahari's Hidden Oasis",
	"Tracing Clear Water Through Papyrus Reeds",
	"Following Life to Where the River Ends",

	"Drifting Down the Mighty Mekong",
	"Tracing a River That Reverses Its Own Flow",
	"Following Giants Through Sediment-Rich Water",
	"Uncovering One of Earth's Richest Rivers",
	"Riding the Monsoon's Rise and Fall",
	"Following Life Along a Restless Current",

	"Plumbing the Ancient Depths of Baikal",
	"Tracing Life in the World's Oldest Waters",
	"Descending Into a Fifth of Earth's Freshwater",
	"Uncovering Species Found Nowhere Else",
	"Following the Only Freshwater Seal Home",
	"Exploring a Lake Older Than Time Itself",

	"Adrift in the Open Pacific Blue",
	"Crossing the Sea Where Nothing Hides",
	"Tracing Vast Migrations Across Empty Water",
	"Following Life Through the Ocean's Sunlit Reach",
	"Venturing Into Earth's Largest Living Space",
	"Drifting Where Sky Meets Endless Sea",

	"Diving Into a Living Rainbow",
	"Exploring a Structure Built by Billions of Lives",
	"Tracing Colour Across the Great Barrier Reef",
	"Uncovering a City Built by Tiny Architects",
	"Descending Into Warm, Sunlit Water",
	"Following Life Across a Fragile Wonder",

	"Sinking Into the Mariana's Crushing Dark",
	"Descending Below Where Sunlight Ends",
	"Tracing Life That Feeds on Falling Snow",
	"Venturing Into Earth's Last Frontier",
	"Uncovering Light in the Deepest Dark",
	"Following Life Under Immense Pressure",

	"Timing the Tides of the Rocky Shore",
	"Tracing Life Between Land and Sea",
	"Enduring the Twice-Daily Crash of Waves",
	"Uncovering Life in the Contested Edge",
	"Following the Rhythm of Rising Water",
	"Clinging On Between High and Low Tide",

	"Prowling the Neon Streets of Tokyo",
	"Tracing Wild Life Among Glass and Concrete",
	"Uncovering Nature's Boldest Survivors",
	"Following Life Through a City That Never Sleeps",
	"Exploring the Wild Side of a Human World",
	"Tracing Adaptation Under Artificial Light"
];